development:
  clients:
    default:
      database: noonoo
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: noonootest
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
