development:
  sessions:
    default:
      database: noonoo
      hosts:
        - localhost:27017
      options:
        consistency: strong

test:
  sessions:
    default:
      database: noonootest
      hosts:
        - localhost:27017
      options:
        consistency: strong

production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        skip_version_check: true
        safe: true
        consistency: strong
